apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.9
        ports:
        - containerPort: 80
###test argocd
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: niginx-kean-svc
#spec:
#  sessionAffinity: None
#  selector:
#    app: nginx
#  ports:
#  - protocol: TCP
#    port: 80
#    targetPort: 8080
#  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: niginx-svc
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
