#! /bin/bash

fail_exit(){
    if [ $1 != 0 ] ; then
        exit 1
    fi
}

report_exit(){
    if [ $1 != 0 ] ; then
        echo "faild"
        exit 1
    fi
}

cat server |while read line ;do ssh -n $line  ; done
cat ceph-mon |while read line ;do ssh -n $line install-zabbix/install_zabbix.sh ceph mon Ceph ; done
cat ceph-osd |while read line ;do ssh -n $line install-zabbix/install_zabbix.sh ceph osd Ceph ; done
cat openstack-controller  |while read line ;do ssh -n $line install-zabbix/install_zabbix.sh openstack controller ;done
cat openstack-computer  |while read line ;do ssh -n $line install-zabbix/install_zabbix.sh openstack computer;done
